dibimbing:
  target: dev_bigquery
  outputs:
    dev_bigquery:
      type: bigquery
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      threads: 1
      timeout_seconds: 300
      job_retries: 1
      keyfile: creds/service_account.json
      location: US
      method: service-account
      priority: interactive
